### ISSUE TITLE
Use "juice" package

### ISSUE THREAD

**Issue by stevenvachon** [RebelMail/html-preflight#18]
to inline styles for gmail support

**Comment by motdotla** [comment]
Thanks for the suggestion @stevenvachon. You could actually do this yourself by making it a small plugin.

Then you can call the plugin in html-preflight in a manner like the following:

```
var preflight = new HTMLPreflight([juice.run.bind(juice)]);
prelight.run(....
```

**Comment by stevenvachon** [comment]
Shouldn't this be an automatic feature so that one needn't write more boilerplate?

**Comment by motdotla** [comment]
Our choice is not to do so. Largely we use this library as part of our process for generating interactive emails. Juice actually messes up some of that interactivity as a result of its design - so it follows we don't want to make it an automatic feature.

**Comment by stevenvachon** [comment]
How about [styliner](https://npmjs.com/styliner)? I found it to be better.

**Comment by motdotla** [comment]
I hadn't seen that one. Thanks for the link! BUT, unfortunately given the same premise, it still has the same problem as noted above.

Feel free to fork with a more opinionated html-preflight though!

**Comment by stevenvachon** [comment]
I'm interested in what it messes up. Perhaps I could contribute to styliner as it hasn't been contributed to in a while.
