### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by M-J-Robbins** [RebelMail/html-preflight#8]

**Comment by motdotla** [comment]
@elbuo8 thoughts on this? Can we break lines when minifying - break them before they reach 990 characters in length?

**Comment by elbuo8** [comment]
We can preserve line breaks but since there are other things that mutate the email too. Might have to write a plugin just for that.

**Comment by motdotla** [comment]
Can we start with just the line breaks here and see how that works out @elbuo8 ?

**Comment by motdotla** [comment]
I think we want the `maxLineLength` method here: https://github.com/kangax/html-minifier
